name: abc
on: [push]
jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting deployment..."
      - uses: actions/checkout@v3
      - name: Test
        run: |
          ls -al
          npm install
          npm run test