name: Deploy to GitHub Pages
on: ["push"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: one
        run: pro
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npx projen build
      - name: List
        run: ls -al
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3